name = "Story Books"
description = "Read some books and increase your sanity! Others around you are also affected by a sanity aura."
author = "andre"
version = "1.0.0"
icon_atlas = ""
icon = ""
dont_starve_compatible = false
dst_compatible = true
client_only_mod = false
all_clients_require_mod = true
api_version = 10
